name: Build and Run Docker Image
run-name: Build and release (started by @${{ github.triggering_actor }})

on:
  push:
    branches:
      - peg/github-action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Build Docker image
      run: |
        docker build -t yocto-builder:base --build-arg MANIFEST=tdx-base.xml ./reproducible-build

    - name: Run Docker container
      run: |
        docker run --rm --env-file yocto-build-config.env \
          yocto-builder:base
